/**
 * Template renderer interface
 */
export interface TemplateRenderer {
  render(template: string, data: Record<string, any>): string;
}

/**
 * Simple template engine for runtime and build-time code generation
 */
export class TemplateEngine implements TemplateRenderer {
  private helpers = new Map<string, (...args: any[]) => any>();

  /**
   * Register a helper function
   */
  registerHelper(name: string, fn: (...args: any[]) => any): void {
    this.helpers.set(name, fn);
  }

  /**
   * Render a template with data
   * Supports {{variable}}, {{helper arg1 arg2}}, and {{#if}}/{{#each}} blocks
   */
  render(template: string, data: Record<string, any>): string {
    let result = template;

    // Replace variables: {{variable}}
    result = result.replace(/\{\{([^}#/][^}]*)\}\}/g, (match, key) => {
      const trimmedKey = key.trim();

      // Check if it's a helper call
      const parts = trimmedKey.split(/\s+/);
      if (this.helpers.has(parts[0])) {
        const helper = this.helpers.get(parts[0])!;
        const args = parts.slice(1).map((arg: string) => this.resolveValue(arg, data));
        return String(helper(...args));
      }

      // Regular variable
      return String(this.resolveValue(trimmedKey, data) ?? '');
    });

    // Handle {{#if condition}}...{{/if}}
    result = result.replace(
      /\{\{#if\s+([^}]+)\}\}([\s\S]*?)\{\{\/if\}\}/g,
      (match, condition, content) => {
        const value = this.resolveValue(condition.trim(), data);
        return value ? content : '';
      }
    );

    // Handle {{#each array}}...{{/each}}
    result = result.replace(
      /\{\{#each\s+([^}]+)\}\}([\s\S]*?)\{\{\/each\}\}/g,
      (match, arrayKey, content) => {
        const array = this.resolveValue(arrayKey.trim(), data);
        if (!Array.isArray(array)) {
          return '';
        }

        return array.map((item, index) => {
          const itemData = { ...data, this: item, index };
          return this.render(content, itemData);
        }).join('');
      }
    );

    return result;
  }

  /**
   * Resolve a value from data using dot notation
   */
  private resolveValue(path: string, data: Record<string, any>): any {
    const parts = path.split('.');
    let value: any = data;

    for (const part of parts) {
      if (value === null || value === undefined) {
        return undefined;
      }
      value = value[part];
    }

    return value;
  }
}

/**
 * Common templates for WXT extensions
 */
export const templates = {
  /**
   * Background script template
   */
  background: `
/**
 * Background script for {{name}}
 * Generated by @wxtools/templates
 */

import { registry } from '@wxtools/app';
{{#each modules}}
import { {{this}} } from './modules/{{this}}';
{{/each}}

// Register modules
{{#each modules}}
registry.register({{this}});
{{/each}}

// Initialize
async function init() {
  try {
    await registry.initialize();
    console.log('Extension initialized');
  } catch (error) {
    console.error('Initialization failed:', error);
  }
}

init();
`,

  /**
   * Content script template
   */
  content: `
/**
 * Content script for {{name}}
 * Generated by @wxtools/templates
 */

import { RPCClient } from '@wxtools/rpc';

const client = new RPCClient();

// Your content script logic here
console.log('Content script loaded');
`,

  /**
   * Popup template
   */
  popup: `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>{{title}}</title>
  <style>
    body {
      width: 300px;
      padding: 16px;
      font-family: system-ui, -apple-system, sans-serif;
    }
    h1 {
      font-size: 18px;
      margin: 0 0 16px 0;
    }
  </style>
</head>
<body>
  <h1>{{title}}</h1>
  <div id="app"></div>
  <script type="module" src="./popup.js"></script>
</body>
</html>
`,

  /**
   * Module template
   */
  module: `
/**
 * {{name}} module
 * Generated by @wxtools/templates
 */

import type { ModuleContract } from '@wxtools/core';

export class {{className}} implements ModuleContract {
  id = '{{id}}';
  name = '{{name}}';
  version = '{{version}}';

  async initialize(): Promise<void> {
    console.log('{{name}} initialized');
    // Your initialization logic here
  }

  async destroy(): Promise<void> {
    console.log('{{name}} destroyed');
    // Your cleanup logic here
  }
}

export default new {{className}}();
`,
};

/**
 * Create a template engine with default helpers
 */
export function createTemplateEngine(): TemplateEngine {
  const engine = new TemplateEngine();

  // Register default helpers
  engine.registerHelper('uppercase', (str: string) => str.toUpperCase());
  engine.registerHelper('lowercase', (str: string) => str.toLowerCase());
  engine.registerHelper('capitalize', (str: string) => 
    str.charAt(0).toUpperCase() + str.slice(1)
  );
  engine.registerHelper('camelCase', (str: string) =>
    str.replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
  );
  engine.registerHelper('pascalCase', (str: string) => {
    const camel = str.replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''));
    return camel.charAt(0).toUpperCase() + camel.slice(1);
  });

  return engine;
}

export * from './generators';
